version: '3.1'

services:

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: eventer
      POSTGRES_DB: eventer
      POSTGRES_PASSWORD: eventer
    ports:
      - "5432:5432"

  email-server:
    image: catatnight/postfix
    restart: always
    environment:
      maildomain: mail.eventer.local
      smtp_user: eventer:eventer
    ports:
      - "25:25"
